name: Ranks
author: awesomehd1
main: net.awesomehd1.Ranks.Main
version: 1.0
commands:
  chatformat:
    description: Toggle whether or not Ace effects chat messages
  rank:
    description: All commands involving ranks
